---
version: 2
plan:
  project-key: SPEC
  key: YAMLSPECS2TEST
  name: Build a Simple Docker Image using specs v2

variables:
  dockerTag: develop

#Stages
stages:
  - Compile something stage:
    - Compile something Job
  - Build the image stages:
    - Build image Job

#Job definition
Compile something Job:
  docker:
    image: "alpine:latest"
  tasks:
    - script:
      - echo "Hola Mundo!!!"
  
  requirements:
    - system.docker.executable
  artifacts:
    - name: test_artifact
      pattern: "**/*"
      shared: true

Build image Job:
  tasks:
    - script:
      - docker build -t "dockerreg-prod.icfolson.com/cicd/spec-tests:${bamboo_dockerTag}" .
  requirements:
    - system.docker.executable